services:
  api:
    command: bun run start:dev 
    container_name: rently-api-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
    env_file:
      - .env.development
    depends_on:
      - db
    networks:
      - rently-network-dev

  db:
    container_name: rently-db-dev
    image: postgres
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - rently-network-dev

networks:
  rently-network-dev:
    driver: bridge
